#!/bin/bash

# Read the input from stdin
while IFS=$'\t' read -r host _ _ _ _ _ _; do
  # Increment the count for each host or IP address
  ((hosts["$host"]++))
done

# Sort the hosts by the number of requests in descending order
sorted_hosts=$(for host in "${!hosts[@]}"; do
  printf "%s\t%s\n" "${hosts[$host]}" "$host"
done | sort -nr | head -n 11 | cut -f2)

# Display the sorted hosts
echo "$sorted_hosts"
